### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grothjef/project6#1]
I see a little bit more slop than I'd like to. Can you delete the unused files and rename `cats.erb` to something that makes more sense for the holidays project?

**Comment by chrisvfritz** [comment]
Any progress on this?

**Comment by grothjef** [comment]
Should be fixed

**Comment by chrisvfritz** [comment]
There are still quite a few unused files in the project. For example, the `holiday` folder and the `install` folder aren't doing anything.

I also see a lot of `.DS_Store` files cluttering up the directory. OS X automatically generates these files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).

And you don't actually need comments such as `# Gemfile` and `# app.rb` in your files. I just include them in code examples sometimes so you know which file the code would appear in. They should be deleted from files they appear in to keep things tidy.

**Comment by grothjef** [comment]
Should be cleaned up

**Comment by chrisvfritz** [comment]
I'm still seeing the `.DS_Store` files on GitHub, which means this didn't make it to an approvable state before the deadline unfortunately.
